# Generated by Django 4.0.6 on 2023-04-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
