# Generated by Django 4.0.6 on 2023-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_options_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='true_false',
        ),
        migrations.AddField(
            model_name='scope',
            name='true_false',
            field=models.BooleanField(default=False, verbose_name='основной'),
        ),
    ]
